name = "n_n_n_Rubiks_Cube"
version = "0.1.0"
defaultTargets = ["n-n-n_rubiks_cube"]

[[lean_lib]]
name = "NNNRubiksCube"

[[lean_exe]]
name = "n_n_n_rubiks_cube"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

